### ISSUE TITLE
Perform shutdown for all nodes at once

### ISSUE THREAD

**Issue by Jelleeelco** [threefoldtecharchive/farmerbot#14]
According to the log, currently nodes are shutdown in a sequence of 5 minutes. If possible, send the shutdown signal to all nodes at once. This will reduce the total uptime of the nodes during periodic checking.

**Comment by brandonpille** [comment]
This should be the case already. But keep in mind that shutting them down takes some time. We have to call the chain. The nodes will then notice an event telling them to shutdown. So it may as well be that it takes a couple of minutes. I would say tops 10 minutes. Can you show me some logs so that I can see what is happening?

**Comment by brandonpille** [comment]
Discussed this offline. The nodes are shutting down all at once but it can take some time before they are all off.
