### ISSUE TITLE
Enable monitoring of farmerbot activity through RMB job

### ISSUE THREAD

**Issue by Jelleeelco** [threefoldtecharchive/farmerbot#15]
Occasionally the ZOS image doesn't download completely on a node during the periodic wakeup. This causes the node to be unavailable. The farmerbot will then stop shutting down any other node (this makes sense).

It would be very helpful to get some monitoring tools on the activity of the farmerbot. Like automated status report via email or telegram bot. Something like this:

- Date
- Node 1234 booted successfully at 00:01
- Node 2345 booted successfully at 00:06
- Node 1234 shut down successfully at 00:15
- Node 2345 shut down successfully at 00:20
- No errors reported

**Comment by scottyeager** [comment]
The node status bot can be adapted to provide this kind of info for `farmerbot` controlled nodes. I'll be working on this as part of a larger update to support changes in 3.9.

**Comment by brandonpille** [comment]
What is the node status bot? Because I received a request from someone from the community asking for a way to get information on what is happening in the farmerbot at any time. So I was thinking of adding a rest api or a websocket messaging service that will expose the events from the farmerbot.

**Comment by Jelleeelco** [comment]
Hi Brandon, 
The status bot is a telegram bot that notifies when a node is down, Scott is the developer behind it (I believe it notifies only when both ping and dashboard are down). One can also ping the nodes, to check if they are online. Now with the farmerbot, ping won't work and the dashboard will show nodes down all the time, hence the status bot needs to be changed.

a rest api / websocket msg service would be ideal of course!

**Comment by brandonpille** [comment]
Ok. I'll create an issue for it so that. @scottyeager what should the rest api / websocket msg service be able to do?

**Comment by scottyeager** [comment]
Hey @brandonpille, just catching up with this. My plan for the node status bot was to use publicly available data from TF Chain along with pings over RMB to determine if nodes are waking up when they should. Also having some data coming directly from the bot could be helpful.

Since the bot is a service I operate that people only interact with through Telegram, it wouldn't be able to reach a web API for farmerbots that aren't exposed to the internet. Offering some RMB endpoints to check on the farmerbot would make more sense for this use case.

Here are a few ideas:
* Simple ping to see that the farmerbot is online
* Return the scheduled wake up time for this farmerbot
* Info on nodes failing to wake up as scheduled
* Retrieve the last power target change and its time

**Comment by brandonpille** [comment]
> Hey @brandonpille, just catching up with this. My plan for the node status bot was to use publicly available data from TF Chain along with pings over RMB to determine if nodes are waking up when they should. Also having some data coming directly from the bot could be helpful.
> 
> Since the bot is a service I operate that people only interact with through Telegram, it wouldn't be able to reach a web API for farmerbots that aren't exposed to the internet. Offering some RMB endpoints to check on the farmerbot would make more sense for this use case.
> 
> Here are a few ideas:
> 
> * Simple ping to see that the farmerbot is online
> * Return the scheduled wake up time for this farmerbot
> * Info on nodes failing to wake up as scheduled
> * Retrieve the last power target change and its time

Opening that up via RMB would make a lot of sense indeed. That would even require almost no change to the code. So I'll go ahead and do that.

**Comment by ashraffouda** [comment]
blocked because of https://github.com/threefoldtech/farmerbot/issues/67#issuecomment-1790639954
