### ISSUE TITLE
Warning farmers when a workload is deployed

### ISSUE THREAD

**Issue by Nelson361** [threefoldtecharchive/farmerbot#25]
Warning farmers when a workload is deployed, either on the app or portal, will help prevent workload downtime.  

Farmers can avoid unnecessary upgrades/alterations or keep these nodes up if they are downsizing with this info.

**Comment by muhamadazmy** [comment]
I think that's not related to zos because the contract creation already raises event on the chain. So the farmer can monitor those events in case one of them is raised by one of his nodes.

Even if we going to build a notification service, it won't be part or related to zos in any mean.

**Comment by muhamadazmy** [comment]
I think this belongs more in the farmerbot because it's aware of the farm, and then can handle grid events, and send an email to the farmer when a contract is created. The farmer then can configure his email in the bot in a private way (since the farmer is the one who starts the bot) hence farmer contact information won't be public

**Comment by ashraffouda** [comment]
blocked because of https://github.com/threefoldtech/farmerbot/issues/67#issuecomment-1790639954
