### ISSUE TITLE
Add random periodic wakeups

### ISSUE THREAD

**Issue by brandonpille** [threefoldtecharchive/farmerbot#36]
People can cheat the current farmerbot by having 2 farms and X nodes and 2*X ssds. The farmer could pretend to have 2 farms with X nodes by setting the periodic wakeup of the first farmerbot to 9 AM and the second to 1PM for example. After the periodic wakeup of farm 1 he can put the ssds in the nodes of farm 2 (before 1PM). The farmer is receiving Tokens for 2*X nodes while he only has X nodes. 

We can discourage this behavior by introducing random periodic wakeups. This could be 1 a week or 5 a month. We might want to look at other solutions to discourage that behavior.

**Comment by GENXGO** [comment]
the problem with my R620 nodes, the following case I have a 4TB ssd in it and a 500 gb SSD in it when booting, but the node simply writes to one or the other disk depending on what you want, which is annoying me only since the last update but I don't think it has anything to do with the Farmbot.

I'm trying to prevent this behavior the next time I wake up, all nodes stay online, if I don't have a solution by tomorrow I'll take out the 500 ssd

As I said, I have the problem with the R620 & 4 TB ssd & a 500 SSD that installs Zero-OS not only on one

**Comment by GENXGO** [comment]
maybe the serial number could also be used to disguise Cheter

**Comment by brandonpille** [comment]
> the problem with my R620 nodes, the following case I have a 4TB ssd in it and a 500 gb SSD in it when booting, but the node simply writes to one or the other disk depending on what you want, which is annoying me only since the last update but I don't think it has anything to do with the Farmbot.
> 
> I'm trying to prevent this behavior the next time I wake up, all nodes stay online, if I don't have a solution by tomorrow I'll take out the 500 ssd
> 
> As I said, I have the problem with the R620 & 4 TB ssd & a 500 SSD that installs Zero-OS not only on one

That's unfortunate to hear. I fail to see the relevance with this issue though... Have you tried reaching out to the team through Telegram?

**Comment by xmonader** [comment]
Are we still planning to do that in 3.11 ?

**Comment by brandonpille** [comment]
Yes
