### ISSUE TITLE
Check transaction volume when relay is down

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/farmerbot#38]
One farmer reported that the farmerbot was generating more transactions than usual during the recent outage of the relay and thus using more TFT than usual. While the amounts of TFT are still small, I think it's worth considering if the behavior of the bot during outages of the relay can be improved in this regard.

**Comment by brandonpille** [comment]
It generates more transactions indeed but those are required. The farmerbot doesn't know when the relay is back online so it keeps trying to power on the nodes and thus executes the transactions. That's how it was designed and it should stay that way else we will encouter situations where it won't do anything anymore because of failures. It should always keep trying.
